---

- name: Configuring web server
  hosts: all
  become: true
  tasks:
    - name: Updating repository index
      ansible.builtin.apt:
        update_cache: true

    - name: Installing apache2 package
      ansible.builtin.apt:
        name:
          - apache2
        state: latest

    - name: Adding PHP support
      ansible.builtin.apt:
        name:
          - libapache2-mod-php
        state: latest
