---

- name: Configuring web servers
  hosts: all
  become: true
  tasks:
    - name: Removing apache2 package
      ansible.builtin.apt:
        name:
          - apache2
        state: absent

    - name: Removing PHP support
      ansible.builtin.apt:
        name:
          - libapache2-mod-php
        state: absent
