---

- name: Configuring web servers
  hosts: all
  become: true
  tasks:
    - name: Updating repository index
      ansible.builtin.apt:
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: Installing apache2 package
      ansible.builtin.apt:
        name:
          - apache2
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Adding PHP support
      ansible.builtin.apt:
        name:
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Updating repository index
      ansible.builtin.yum:
        update_cache: true
      when: ansible_distribution == "RedHat" and ansible_distribution_version == "9.0"

    - name: Installing apache2 package
      ansible.builtin.yum:
        name:
          - httpd
        state: latest
      when: ansible_distribution == "RedHat" and ansible_distribution_version == "9.0"

    - name: Adding PHP support
      ansible.builtin.yum:
        name:
          - php
        state: latest
      when: ansible_distribution == "RedHat" and ansible_distribution_version == "9.0"
