---

- name: Configuring web servers
  hosts: all
  become: true
  tasks:
    - name: Installing apache and php packages
      ansible.builtin.package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: true
